server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#    service-url:
#      defaultZone: http://eureka2:8762/eureka/
#  server:
#    enableSelfPreservation: false
  instance:
    prefer-ip-address: true

